import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import Navbar from '@/components/Navbar';
import { StoreProvider } from '@/store/StoreProvider';

import './globals.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Navbar />
          <main className="bg-gray-900 min-h-screen p-24">
            {children}
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
